[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

lib_deps =
  adafruit/Adafruit MCP23017 Arduino Library @ ^2.3.2
  bblanchon/ArduinoJson @ ^7
  knolleary/PubSubClient @ ^2.8
  ottowinter/ESPAsyncWebServer-esphome @ ^3.1.0
  khoih-prog/AsyncWebServer_ESP32_W5500 @ ^1.6.4
  khoih-prog/WebServer_ESP32_W5500 @ ^1.5.3

build_flags =
  -D CORE_DEBUG_LEVEL=0
  -D ASYNCWEBSERVER_REGEX
  -D ARDUINOJSON_USE_LONG_LONG=1
  -D WDT_ENABLE=1
  -D W5500_ETHERNET
  -D ETH_W5500_CS=5
  -D ETH_W5500_INT=-1
  -D ETH_W5500_RST=4
  -D ETH_W5500_MISO=19
  -D ETH_W5500_MOSI=23
  -D ETH_W5500_SCK=18

extra_scripts =
  pre:tools/gzip_ui.py
  pre:tools/patch_w5500.py
