#pragma once
#include <Arduino.h>
bool net_begin_eth_w5500_async();
bool net_begin_wifi_sta_async();
bool net_begin_ap();
void net_loop();
bool net_have_ip();
String net_ip_str();
bool net_is_ap();
String net_mode_str();
